### PR TITLE
Fix reward display and improve format configuration

### PR DESCRIPTION
**Pull request by addstar**
Hello, thanks for making this great plugin! We are planning to use it on our server network but have made some changes that you might be interested in.

This PR contains the following changes:
* Fixes the reward display in the achievement list output (/aach list)
* Adds ability to hide reward in list output (defaults to false)
* Adds several formatting options to customise the output of the achievement list (received/not-received prefix, achievement name format, list item separator)
* Also code clean ups (simplified lore creation and achievement title output)
* Add ability to disable/hide entire categories from GUI and prevent receiving the achievements
* Add ability to track powered creeper kills

I will also be adding functionality to hide/disable specific categories, in a future PR.

### CODE REVIEW

**Comment by PyvesB** [comment]
Hello addstar,

Thanks for your contribution and your interest in AdvancedAchievements!

- Fixes the reward display in the achievement list output (/aach list) -> Great, I hadn't noticed it wasn't working correctly anymore.
- Adds ability to hide reward in list output (defaults to false) -> Great, I'm sure some users will appreciate this feature.
- Adds several formatting options to customise the output of the achievement list (received/not-received prefix, achievement name format, list item separator) -> Good addition also!
- Also code clean ups (simplified lore creation and achievement title output) -> I must admit that this was not the cleanest nor simplest part of the code, a bit of cleaning won't hurt!
- Add ability to disable/hide entire categories from GUI and prevent receiving the achievements -> Actually there were ways of doing this previously, in a separate way; either by setting the category to {} to disable that category, or setting the name of the category to "" in the language file to hide it from the GUI (but without disabling the category). Furthermore, your current implementation lets the statistics continue on increasing (as the listeners are still set in AdvancedAchievements.java), so I'm afraid this will be really confusing for users.
- Add ability to track powered creeper kills -> Nice addition, I'll add some documentation about it!

I'll accept the pull request as is, and will rework point number 5 (feel free to also do another pull request, you might have a better idea than I do). Thanks again! ;-)

Cheers,

Pyves

**Comment by addstar** [comment]
Thanks for the quick response!

Regarding point 5, I tried disabling a category by doing `Snowballs: {}` but it just gave errors when reading the config. Are you sure this is the right way to do it?

It's simple enough to also prevent stats collection with the DisabledCategories. I can submit another PR which has this feature if you'd like? It could either unregister the event handler or just ignore events called for disabled categories. The only issue with unregistering is it would have to know how to register them again if items were removed from the "disabled" list and you used "/aach reload".

Let me know your thoughts, I'm happy to go either way.

On unrelated points:
1) I'd like to add "cause" to the player deaths, but it would make it a "multiple achievement" style option, and require a schema change. Would you be willing to accept this change if it effects existing users?
2) I'd like to add an "ALL" option to all "multiple achievement" categories (Kills, Break, Place, etc) so you could give an achievement to X total,regardless of type. But it would mean it could be possible to receive two achievements in the same event and have an additional counter ("ALL"). Are you ok with this?
3) Have you considered adding achievements made from multiple stats (eg. tame 10 wolves + tame 10 horses)? It would be tricky to implement and also find a clean configuration method for it, but I think it would really bring additional power to the plugin.

With all my changes, I'd prefer to submit them back to you (it's only fair) and add configuration options so it doesn't adversely affect your existing users.. hopefully I can continue to contribute to your code base without having to completely deviate from your code (we have enough projects to maintain already ;)

_(Sorry for the long post!)_

**Comment by addstar** [comment]
Oh and as for the credit, I really don't mind either way. We do this for our own server network :smile: 
Feel free to mention our server "[AddstarMC](http://addstar.com.au/)" though :wink: haha

**Comment by PyvesB** [comment]
That's weird, the {} seemed to be working when it tested it, will have to look into that again. I guess reregistering and unregistering the listeners isn't that important, I can simply add a statement in the config saying that /aach reload does not handle the DisabledCategories. It will be complicated otherwise, and would bring an overhead to the command. But I can take care of this part if you prefer working on the other points you mentioned. ;-)

1) Sounds like a good idea! I would rather have it not affect previous users, therefore updating the config file accordingly and rebuilding a new database table (rebuild as tables cannot be altered in SQlite contrarily to MySQL or other mainstream database systems; I can take care of the database upgrade part if you like). The cause could be "NA" or whatever for the old values in the new table, and would only be counted as an "ALL" category you mentioned in point 2).
2) The "ALL" idea also seems nice, it could easily be retrieved by a SQL query on the existing table. For the two achievements in the same event, we would have to add a small delay, it would be more professional. ;-)
3) I've thought about it and it would indeed be quite tricky to implement in an efficient way. I'm also convinced that users would mess things up in the config and not understand what's going on, so I'm not sure it's the best idea! Maybe achievements based on other ones would be simpler than directly considering the stats.

Cheers,

Pyves

**Comment by PyvesB** [comment]
There were a few issues with your /aach list modifications:
- all the achievements automatically had the obfuscated effect.
- if a player had set a color for his achievement, it would "bypass" the obfuscation effect if not yet received; I reimplemented the regex pattern, which deals with this issue.

Hopefully after my latest commits it works well. ;-)

Also I took care of the DisabledCategories directly blocking the creation of listeners whenever possible. I have to test all this now! ^^

By the way, why did you allocate a string builder with size 100 in /aach list?

**Comment by addstar** [comment]
Sorry for the late reply.. I've been busy on other things and haven't had time to work on this. I'll be doing some more work on this very soon. I'll check out what you've done and happy to help work on any remaining features/issues we discussed.

Is there anything in particular you'd like to handle yourself or want me to work on?

Oh and the StringBuilder 100 was to make the initial allocation more efficient. They suggest allocating a "typical" size so you can minimise the need for resizing.

Also, I forgot to test the obfuscation feature.. sorry about that, we don't use it.

**Comment by PyvesB** [comment]
I guess it makes sense for the StringBUilder, 100 does seem like a reasonable number.

Well, I think all the things we discussed are more or less resolved; I think it would now be nice to focus on ideas 1) and 2) now. Also, if you've got ideas to further improve the GUI, please share them; all the slots are currently full, and some users tend to stack up really many achievements in a single category, so I'm trying to think of ways to make it better/more flexible. ;-)

**Pull request merged**
