### PR TITLE
Fix unlimited potion stats glitch

### PR DESCRIPTION
**Pull request by rafael59r2**

### CODE REVIEW

**Comment by rafael59r2** [comment]
Wait, I wrote wrongly the for statment

**Comment by PyvesB** [comment]
Hello @rafael59r2 , thanks for your interest in the project! However, I don't think this would work. According to the Bukkit API, the event is fired when "the brewing of the contents inside the Brewing Stand is complete". Similarly to what happens with a furnace, brewing will likely complete when the player isn't around and therefore when they aren't viewing the inventory. 😉

**Comment by rafael59r2** [comment]
But You can use the same potion multiple times to increase the stats

**Comment by PyvesB** [comment]
> But You can use the same potion multiple times to increase the stats

Yes, that's a known limitation, though mitigated by the cooldown. See #559 for example.

The only proper solution that I can think of would be to keep track of player interactions with brewing stands in a database, but that would be quite a complex solution probably not worth the effort. An in-memory data structure could work as well, but would still allow some abuse when the server is restarted/reloaded or when the player disconnects.

Alternatively, you could raise an issue on the [Spigot tracker](https://hub.spigotmc.org/jira/secure/Dashboard.jspa) to see if they could add players to `BrewEvents`.

**Comment by rafael59r2** [comment]
Ok, thanks.

**Pull request closed without merging**
