### PR TITLE
Process playtime achievement eligibility in parallel to speed up when there are a large number of players.

### PR DESCRIPTION
**Pull request by metalshark**
Fixes issue 687.

### CODE REVIEW

**Comment by PyvesB** [comment]
Bukkit is generally not thread safe, for example the [Java documentation ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/scheduler/BukkitScheduler.html) states that "asynchronous tasks should never access any API in Bukkit". The code path covered by `updateTime` invokes the `Player` API, configuration file APIs, the event API through `Bukkit.getPluginManager().callEvent`, etc. Parts of Advanced Achievements itself in this code path are not thread safe either.

Unfortunately, I don't think this is a safe change. 😉

**Comment by metalshark** [comment]
Yup Bukkit isn’t thread safe, here the main thread will wait for the parallel to finish before proceeding and none of the items inside the parallel interact. Parallel streams were designed precisely for adding this to non-thread safe code. Had to dig into the code of Paper and Spigot to check. Appreciate the hesitance here.

**Comment by metalshark** [comment]
Please note that as the main synchronous thread of the server is sat wait for the parallel to finish, this isn’t what the “asynchronous task” warning in the Bukkit documentation is referring to. But let’s say you made state changes using the API in any of parallel task, then that could end very badly.

**Comment by PyvesB** [comment]
The problem here is that the `updateTime` may run in a parallel thread which is not the main server thread ("may", because the JVM can choose so execute the stream synchronously even though `parallelStream` is specified, for example if it contains only one element; this makes testing hard).

Some Bukkit APIs cannot be called in parallel, for example `Bukkit.getPluginManager().callEvent` which will be called from within `updateTime` if a player is eligible for the next `PlayedTime` threshold. If that method is called from a thread that isn't the main server thread, it will throw `java.lang.IllegalStateException: XXXEvent cannot be triggered asynchronously from another thread`.

Another example is some of Advanced Achievement's data structures in `CacheManager` which aren't thread safe (e.g. `receivedAchievementsCache = new HashMap<>()`). `updateTime` may cause these to be written to when checking whether a player has already received a `PlayedTime` achievement. Several threads may be doing so in parallel following this change, leading to undefined behaviour as these are not `ConcurrentHashMap`s. Everything on the code path would need to be carefully checked, including in Bukkit's internals. We would need to then think about other kinds of race conditions, as some of the code has been built around a "one writer, multiple readers" contract, and this may change that. All of this is probably error-prone and not worth the effort!

Does this make sense? I'm happy to be proven wrong, but I do think this change risks partly breaking `PlayerTime` achievements. 😉

**Pull request closed without merging**
