### PR TITLE
Update lang-CN.yml

### PR DESCRIPTION
**Pull request by BillZhucn**

### CODE REVIEW

**Comment by BillZhucn** [comment]
I also translated the config file to Chinese. Could I commit it with name config-CN.yml ?

**Comment by PyvesB** [comment]
You could, however, there's no code in the plugin that allows to easily make use of it as there is for the lang file (`LanguageFileName` config parameter). People would have to open it up from this repository in their browser. 😉

**Comment by BillZhucn** [comment]
> You could, however, there's no code in the plugin that allows to easily make use of it as there is for the lang file (`LanguageFileName` config parameter). People would have to open it up from this repository in their browser. 😉

I know that. But then people can just copy and paste to use the translated config file and translated achievement settings.

**Comment by PyvesB** [comment]
Yes, feel free to submit if you want ! :)

**Pull request merged**
