### PR TITLE
Add Advancements Category

### PR DESCRIPTION
**Pull request by CrabMustard**
This may seem a little redundant given the nature of this plugin, however I did this to allow myself to reward players for completing advancements added by a data pack. There are hundreds of them, so I added this category to track completion and reward players.

### CODE REVIEW

**Comment by CrabMustard** [comment]
Not sure what I am doing with the formatter. It does not seem to be changing the correct things.

**Comment by CrabMustard** [comment]
@PyvesB I'm running the formatting, and it gets through validation on my end, but no dice on here. I've been running them through command line. Any suggestions?

**Comment by CrabMustard** [comment]
Ran the formatter on Ubuntu, and it had the right result this time.

**Comment by PyvesB** [comment]
Hi @CrabMustard, thanks for the contribution! Sorry about the trouble with the formatting, the line endings enforced by the formatter were probably competing with the ones configured by Git!

Two main comments:
* could you please add `updateSetting(gui, "Advancements.Item", "gold_ingot");` to _FileUpdater_.
* you're right to say that it may seem redundant to some users. Maybe it's worth adding the category to `DisabledCategories` in the default configuration?

**Comment by PyvesB** [comment]
FYI, I've renamed the category from `Advancements` to `AdvancementsCompleted`. Advancements is quite an overloaded word, it would have been confusing (e.g. someone asking for support stating "I've got a problem with Advancements").

**Pull request merged**
