### PR TITLE
fix nullpointer when clicking empty slots in list gui

### PR DESCRIPTION
**Pull request by jascotty2**
(also added conversion for long time values, when manually importing a sqlite database)

### CODE REVIEW

**Comment by PyvesB** [comment]
Thanks for your contribution @jascotty2 ! Out of fascination, when can that `NullPointerException` happen, I am unable to reproduce the error in game ? Also could you please run `mvn formatter:format` to make the CI server happy? 😄

**Comment by jascotty2** [comment]
Happens in 1.14.1 when clicking on empty space (select a category, then click on a slot that doesn't have an item)

I can re-format the db line when I'm back home, sure!

**Comment by jascotty2** [comment]
Fixed!

**Comment by PyvesB** [comment]
> Happens in 1.14.1 when clicking on empty space (select a category, then click on a slot that doesn't have an item)

Indeed, this seems to be a change in behaviour in Minecraft 1.14, good spot! Let's get this merged!

**Pull request merged**
