### PR TITLE
HikariCP

### PR DESCRIPTION
**Pull request by metalshark**
Converted database connections to use the Hikari Connection Pool.

### CODE REVIEW

**Comment by PyvesB** [comment]
Interesting pull request, thanks for sharing your work! Have you benchmarked the plugin's performance with these changes? What is the expected speedup?

**Comment by metalshark** [comment]
The latency after periods of inactivity on MySQL/Postgres is the improvement you’ll see right now as it truly keeps connections alive. This also allows for patches in the future where multiple concurrent writes can occur with a connection pool.

**Comment by metalshark** [comment]
Should also allow for more refactoring/tidying up of the database code (it was pretty clean already to be fair).

**Comment by PyvesB** [comment]
Okay, thanks for the info! :)

I built your branch yesterday evening (missing last commit, _Flattened nested/shared connections._), but did not have time to test it until now. I started with a fresh plugin installation (i.e. fully deleted the _AdvancedAchievements_ server) but unfortunately I'm observing the following stack trace appeared when I connected to the server:

````
[20:45:40] [Server thread/INFO]: [AdvancedAchievements] Player DarkPyves received the achievement: connect_1 (Good Choice)
[20:45:44] [pool-8-thread-1/ERROR]: [AdvancedAchievements] Database write error while updating connection date and count:
java.sql.SQLException: Connection is closed
        at com.zaxxer.hikari.pool.ProxyConnection$ClosedConnection.lambda$getClosedConnection$0(ProxyConnection.java:494) ~[?:?]
        at com.sun.proxy.$Proxy29.prepareStatement(Unknown Source) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:316) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$updateAndGetConnection$12(AbstractDatabaseManager.java:447) ~[?:?]
        at com.hm.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) ~[?:?]
        at com.hm.achievement.db.SQLWriteOperation.lambda$executeOperation$0(SQLWriteOperation.java:33) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
````

**Comment by PyvesB** [comment]
With the latest commit I'm seeing a different stack trace on connection:
````
[21:26:11] [Server thread/INFO]: [AdvancedAchievements] Player DarkPyves received the achievement: connect_1 (Good Choice)
[21:26:15] [pool-8-thread-1/ERROR]: [AdvancedAchievements] Database write error while updating connection date and count:
org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: connections)
        at org.sqlite.core.DB.newSQLException(DB.java:941) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.core.DB.newSQLException(DB.java:953) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.core.DB.throwex(DB.java:918) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:134) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.core.DB.prepare(DB.java:257) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:47) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:35) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:241) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:205) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:316) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.lambda$updateAndGetConnection$13(AbstractDatabaseManager.java:451) ~[?:?]
        at com.hm.achievement.db.SQLWriteOperation.attemptWrites(SQLWriteOperation.java:45) ~[?:?]
        at com.hm.achievement.db.SQLWriteOperation.lambda$executeOperation$0(SQLWriteOperation.java:33) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
````

**Comment by metalshark** [comment]
Will have a looksie tomorrow

**Comment by metalshark** [comment]
Took the pool connection limit out for file based - reinstating it should
fix

**Comment by PyvesB** [comment]
The errors on connection seem to have gone away, however, I've got a new exception on startup whenever I stop and restart the server with an existing database:
````
[21:37:45] [Server thread/ERROR]: Error occurred while enabling AdvancedAchievements v5.15.1 (Is it up to date?)
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: No suitable driver found for
        at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:589) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at com.hm.achievement.db.AbstractDatabaseManager.initialise(AbstractDatabaseManager.java:109) ~[?:?]
        at com.hm.achievement.lifecycle.PluginLoader.loadAdvancedAchievements(PluginLoader.java:141) ~[?:?]
        at com.hm.achievement.AdvancedAchievements.onEnable(AdvancedAchievements.java:50) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:462) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:376) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:456) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:266) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:783) [craftbukkit15.jar:git-Spigot-f39a89e-f777640]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.sql.SQLException: No suitable driver found for
        at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191) ~[?:?]
        at org.h2.jdbcx.JdbcDataSource.getConnection(JdbcDataSource.java:160) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:354) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:473) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:554) ~[?:?]
        ... 14 more
````

**Comment by PyvesB** [comment]
Closing for now, feel free to reopen when it's ready. :wink:

**Pull request closed without merging**
