### PR TITLE
Update lang-RU.yml

### PR DESCRIPTION
**Pull request by Russia9**
Better translate

### CODE REVIEW

**Comment by PyvesB** [comment]
Hello @Russia9,

Thank you for your contribution. There are some new texts that have appeared since this file was last translated (see the official English translation [here](https://github.com/PyvesB/AdvancedAchievements/blob/master/advanced-achievements-plugin/src/main/resources/lang.yml)). Would you like to have a go at translating them as well? 😉 

Cheers,

Pyves

**Comment by Russia9** [comment]
Ok, I'll do it

**Comment by PyvesB** [comment]
@Russia9 how's it going with the translation? ^^

**Comment by AviRendall** [comment]
i can give lang_ru

**Comment by PyvesB** [comment]
@AviRendall has proposed an updated version in #410, so I'm going to close this pull request. Feel free to open a new one if you have any improvement suggestions. 😉

**Pull request closed without merging**
