### PR TITLE
Add auto check version

### PR DESCRIPTION
**Pull request by montlikadani**

### CODE REVIEW

**Comment by PyvesB** [comment]
Hello @montlikadani !

Thanks for your pull request, but unfortunately I don't think it's in a working state. The version number ends up not being specified anywhere in _pom.xml_, and Maven will refuse to build the project. Also, as per [my comment](https://github.com/PyvesB/AdvancedAchievements/pull/349#issuecomment-386731788) in #349, we should keep the versions hard-coded in languages other than the official English translation. 😉 

Cheers,

Pybes

**Comment by montlikadani** [comment]
Yeah, I understand... Then I'll close it. I forgot what he wrote then.

**Comment by montlikadani** [comment]
But anyway I did this to avoid making unnecessary commit to a version leap.

**Comment by PyvesB** [comment]
The version leap commit is indeed not fundamental, but it does make it easier to see which commits were made from one version to another ^^

**Pull request closed without merging**
